### ISSUE TITLE
Проблема с именем test_google_should_find_selene.py

### ISSUE THREAD

**Issue by fonbeauty** [qa-guru/getting-started-python#5]
Стоит переименовать файл test_google_should_find_selene.py - убрать "test_" в начале
У некоторых студентов Пайчарм считает, что это тесты и запускает скрипт раннером пайтеста. В результате запуска, пайтест тесты не находит и выполнение завершается с exit code 5

**Comment by sashkir7** [comment]
Добрый день. 
Файл успешно переименовал - большое спасибо

**Comment by yashaka** [comment]
Не думаю что это было хорошей идеей... Я бы сказал, что то что вылазит такая ошибка – это полезно, и как раз студенты могут разобраться как работает пайшарм. На самом деле оно у них запускается как тест - скорее всего уже после того как они установят pytest но возможно еще не успеют закинуть код внуть функции test_...

Возможно есть и другие нюансы когда пайшарм делает не совсем то что студент ожидает, но как мне кажется - лучше исследовать причину и задокументировать ее в FAQ таким образом научить студентов уму разуму а не подстроить проект под них... Тем более что на уроке я не просто так называю файл начиная с test, я сразу стараюсь показывать хороший пример именования тест кейсов... 

Так то ... Можно конечно оставить как есть, вам же вдруг что FAQ писать:) Но я бы на своем курсе такого не делал:) Считаю это не совсем эффективно с точки зрения методологии.
